CREATE TABLE Character_Types_table
(
  V_CHARACTER CHARACTER(255),
  V_CHAR CHAR,
  V_VARCHAR VARCHAR(255),
  V_VARCHAR2 VARCHAR2(255),
  V_NCHAR NCHAR(30),
  V_NVARCHAR2 NVARCHAR2(255),
  V_int INT,
  V_INTEGER INTEGER
);